/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.practica.jjp;

import org.junit.Test;

import io.restassured.http.ContentType;

import static org.junit.Assert.*;

import static io.restassured.RestAssured.*;

public class AppTest {

    static String webSite = "https://petstore.swagger.io/v2";
    static String user = "/user";
    static String userName = "/user/{username}";

    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testPost() {
        User data = new User(228, "vladpogba", "Vlad", "Vlados", "pogba@example.ru", "pass1234", "+79127654321", 0);
        given().accept(ContentType.JSON)
            .contentType(ContentType.JSON)
            .body( data.getJson().toString() )
        .when()
            .post(webSite + user)   
        .then()
            .statusCode(200);

    }
    
    @Test public void testGet() {
        User data = new User(228, "vladpogba", "Vlad", "Vlados", "pogba@example.ru", "pass1234", "+79127654321", 0);
        given()
            .accept(ContentType.JSON)
        .when()
            .get(webSite + userName, data.userName)   
        .then()
            .statusCode(200);

    }

    @Test public void testPut() {
        User data = new User(228, "vladpogba", "Vlad", "Vlados", "pogba@example.ru", "pass1234", "+79127654321", 0);
        given()
            .accept(ContentType.JSON)
            .contentType(ContentType.JSON)
            .body( data.getJson().toString() )
        .when()
            .put(webSite + userName, data.userName)   
        .then()
            .statusCode(200);


    }
    @Test public void testDelete() {
        User data = new User(228, "vladpogba", "Vlad", "Vlados", "pogba@example.ru", "pass1234", "+79127654321", 0);
        given()
            .accept(ContentType.JSON)
        .when()
            .delete(webSite + userName, data.userName)   
        .then()
            .statusCode(200);



    }
}
